### ISSUE TITLE
MDC Select Validation

### ISSUE THREAD

**Issue by arjendeblok** [aurelia-ui-toolkits/aurelia-mdc-web#18] opened 2020-10-22 14:34 UTC
I have a form with a **required**
1. text field
2. select (with object binding)

I have a problem to get validation implemented so that both controls behave in the same way.
What I would like is that if the control gets focus, the user does not fill in anything and moves to the next control then an error message is shown indicating that the field is required.

For a _text field_ this works as expected. I have two ways of doing that: 
1. with the `required` attribute and an helper text with a `validation` attribute;
2. with Aurelia validation with a `validate` binding behavior (without a helper text with a `validation` attribute).

For a _select_ this only works in one way correctly
1. with the `required` attribute and an helper text with a `validation` attribute

With Aurelia validation this does **not** work as I would like it
1. With Aurelia validation and a `validateOnChange` binding behavior the error is only shown the user if you first select a value and then clear the value.
2. With Aurelia validation and a `validate` binding behavior then the error is shown too early (when the menu is opened)

Is there a way to use a _select_ with Aurelia validation and the desired behavior?

**Comment by MaximBalaganskiy** [comment] 2020-10-23 00:36
The issue is that select emits blur when a dropdown receives focus. Not sure if this can be prevented, I'll have a look

**Comment by arjendeblok** [comment] 2020-10-23 06:19
If I move the blur emit `this.emit('blur', {}, true);` from `MdcSelect.handleBlur` to `MdcSelect.handleMenuClosed` then it works as expected.

**Comment by MaximBalaganskiy** [comment] 2020-10-23 08:42
If you do that then just tabbing through the select will not validate it.

**Comment by MaximBalaganskiy** [comment] 2020-10-23 09:25
I can do
```ts
handleBlur() {
  this.foundation?.handleBlur();
  if (!this.root.classList.contains(cssClasses.ACTIVATED)) {
    this.emit('blur', {}, true);
  }
}
```
This will prevent validation when the menu is open. But if a user tabs out of this open menu the control will not be validated since the select itself is not getting the focus back. This can be solved, as you suggested, by emitting `blur` on menu close, but, if the menu was closed by clicking on the select itself it will trigger validation even though focus is "conceptually" is still on the select. What are your thoughts?

**Comment by MaximBalaganskiy** [comment] 2020-10-23 09:29
Ok, I think I got it

**Closed as completed** 2020-10-23 09:33 UTC

**Comment by arjendeblok** [comment] 2020-10-23 09:47
Nice!
